package teams.xianlin.com.teamshit.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table GROUPS.
 */
public class Groups implements Serializable {

    public final static int GroupBoastGame = 1;//吹牛

    public final static int GroupTwentyGame = 2;//21点

    /**
     * Not-null value.
     */
    private String GroupId;
    /**
     * Not-null value.
     */
    private String Name;
    private String PortraitUri;
    private Integer Role;
    private Integer GroupType;
    private Long TimeStamp;
    private String Introduce;
    private Integer Number;

    public Groups() {
    }

    public Groups(String GroupId) {
        this.GroupId = GroupId;
    }

    public Groups(String GroupId, String Name, String PortraitUri, Integer Role, Integer GroupType, Long TimeStamp, String Introduce, Integer Number) {
        this.GroupId = GroupId;
        this.Name = Name;
        this.PortraitUri = PortraitUri;
        this.Role = Role;
        this.GroupType = GroupType;
        this.TimeStamp = TimeStamp;
        this.Introduce = Introduce;
        this.Number = Number;
    }

    /**
     * Not-null value.
     */
    public String getGroupId() {
        return GroupId;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setGroupId(String GroupId) {
        this.GroupId = GroupId;
    }

    /**
     * Not-null value.
     */
    public String getName() {
        return Name;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setName(String Name) {
        this.Name = Name;
    }

    public String getPortraitUri() {
        return PortraitUri;
    }

    public void setPortraitUri(String PortraitUri) {
        this.PortraitUri = PortraitUri;
    }

    public Integer getRole() {
        return Role;
    }

    public void setRole(Integer Role) {
        this.Role = Role;
    }

    public Integer getGroupType() {
        return GroupType;
    }

    public void setGroupType(Integer GroupType) {
        this.GroupType = GroupType;
    }

    public Long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(Long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public String getIntroduce() {
        return Introduce;
    }

    public void setIntroduce(String Introduce) {
        this.Introduce = Introduce;
    }

    public Integer getNumber() {
        return Number;
    }

    public void setNumber(Integer Number) {
        this.Number = Number;
    }

}
