package teams.xianlin.com.teamshit.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table MESSAGE_USER.
 */
public class MessageUser {

    /**
     * Not-null value.
     */
    private String UserId;
    private String PortraitUri;
    private String DisplayName;

    public MessageUser() {
    }

    public MessageUser(String UserId, String PortraitUri, String DisplayName) {
        this.UserId = UserId;
        this.PortraitUri = PortraitUri;
        this.DisplayName = DisplayName;
    }

    /**
     * Not-null value.
     */
    public String getUserId() {
        return UserId;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUserId(String UserId) {
        this.UserId = UserId;
    }

    public String getPortraitUri() {
        return PortraitUri;
    }

    public void setPortraitUri(String PortraitUri) {
        this.PortraitUri = PortraitUri;
    }

    public String getDisplayName() {
        return DisplayName;
    }

    public void setDisplayName(String DisplayName) {
        this.DisplayName = DisplayName;
    }

    @Override
    public String toString() {
        return "MessageUser{" +
                "UserId='" + UserId + '\'' +
                ", PortraitUri='" + PortraitUri + '\'' +
                ", DisplayName='" + DisplayName + '\'' +
                '}';
    }
}
